#! /bin/sh
# Encode root or first arg as UTF-16 in big endian with a byte order mark.
# Awk adds the byte order mark.
# Output to standard out.
# To check output, pipe the output to iconv -f UTF-16 -t UTF-8 | od -c

echo -n ${1:-root} | iconv -f UTF-8 -t UTF-16BE \
    | awk '{printf("\376\377%s",$0)}'
